name = "RayTracer"
uuid = "74ea93b9-f251-46a3-9cde-0c1c250040ba"
authors = ["Andrea Baroffio <andrea.baroff2000@gmail.com>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ColorTypes = "0.12.0"
Crayons = "4.1.1"
Images = "0.26.2"
JuliaFormatter = "1.0.62"
Revise = "3.7.2"
Test = "1.11.0"
