name = "RayTracer"
uuid = "74ea93b9-f251-46a3-9cde-0c1c250040ba"
authors = ["Andrea Baroffio <andrea.baroff2000@gmail.com>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ColorTypes = "0.12.0"
Crayons = "4.1.1"
Images = "0.26.2"
LinearAlgebra = "1.11.0"
Test = "1.11.0"
